### ISSUE TITLE
Less debug logging without DEBUG

### ISSUE THREAD

**Issue by foolip** [sadym-chromium/bidiInChromeContext#2]
There's currently a lot of output even when not using the `DEBUG` environment variable. Can this be reduced to just something like "Listening on port 8000" and logging errors? (When running tests, logging only fatal errors, since bad input is deliberately used.)

**Comment by sadym-chromium** [comment]
fixed in https://github.com/sadym-chromium/bidiInChromeContext/commit/26370d21ea39af0dc54117e9653190c6c6c5be85

**Comment by foolip** [comment]
Thanks @sadym-chromium, I can confirm no output when just starting the server now.
