### ISSUE TITLE
Make _commandCallbacks a Map

### ISSUE THREAD

**Issue by mathiasbynens** [sadym-chromium/bidiInChromeContext#8]
It looks like it's being used as a Map, so let's make it one: https://github.com/sadym-chromium/bidiInChromeContext/blob/5c771c76449dc9b4bba8d5e60a9d604a7a22800a/src/mapperServer.ts#L13

**Comment by sadym-chromium** [comment]
Fixed in `86c9b039128ff5bdf0aec4f3506a567474ac3c93`
