### ISSUE TITLE
Set up automatic code formatting

### ISSUE THREAD

**Issue by mathiasbynens** [sadym-chromium/bidiInChromeContext#9]
This would make it easier to collaborate by reducing the need to discuss code style etc.

We could use Prettier. Here's Puppeteer's config: https://github.com/puppeteer/puppeteer/blob/main/prettier.config.js

**Comment by sadym-chromium** [comment]
https://github.com/sadym-chromium/bidiInChromeContext/commit/a87cde4798a07d1559dc210599cf5504fdb13100
